# Lista de disciplinas extraída de app.py para modularidade
disciplinas = [
    {"nome": "Cálculo I", "inicio": 8, "fim": 10, "dias": ["Segunda", "Quarta"],
     "atividades": [{"nome": "Resolver exercícios (Cálculo I)", "duracao": 3, "deadline_day": "Quarta", "deadline_hour": 20}]},
    {"nome": "Álgebra Linear", "inicio": 9, "fim": 11, "dias": ["Segunda"],
     "atividades": [{"nome": "Praticar problemas (Álgebra Linear)", "duracao": 2, "deadline_day": "Segunda", "deadline_hour": 23}]},
    {"nome": "Física I", "inicio": 10, "fim": 12, "dias": ["Segunda"],
     "atividades": [{"nome": "Estudo teórico (Física I)", "duracao": 2, "deadline_day": "Terça", "deadline_hour": 18}]},
    {"nome": "Arquitetura e Desenho", "inicio": 8, "fim": 10, "dias": ["Terça", "Quinta"],
     "atividades": [{"nome": "Desenho - exercício", "duracao": 2, "deadline_day": "Quinta", "deadline_hour": 20}]},
    {"nome": "Lógica de Programação", "inicio": 9, "fim": 11, "dias": ["Terça"],
     "atividades": [{"nome": "Resolver exercícios (Lógica)", "duracao": 2, "deadline_day": "Quarta", "deadline_hour": 22}]},
    {"nome": "Estruturas de Dados 1", "inicio": 10, "fim": 12, "dias": ["Terça"],
     "atividades": [{"nome": "Prática (Estruturas 1)", "duracao": 3, "deadline_day": "Sexta", "deadline_hour": 18}]},
    {"nome": "Matemática Discreta 1", "inicio": 14, "fim": 16, "dias": ["Quarta"],
     "atividades": [{"nome": "Listas de exercícios (Discreta 1)", "duracao": 2, "deadline_day": "Quinta", "deadline_hour": 20}]},
    {"nome": "Requisitos de Software", "inicio": 15, "fim": 17, "dias": ["Quarta"],
     "atividades": [{"nome": "Leitura e resumo (Req. SW)", "duracao": 1, "deadline_day": "Sexta", "deadline_hour": 12}]},
    {"nome": "Matemática Discreta 2", "inicio": 8, "fim": 10, "dias": ["Quinta"],
     "atividades": [{"nome": "Exercícios (Discreta 2)", "duracao": 2, "deadline_day": "Sexta", "deadline_hour": 20}]},
    {"nome": "Engenharia e Ambiente", "inicio": 10, "fim": 12, "dias": ["Quinta"],
     "atividades": [{"nome": "Relatório (Eng.Ambiente)", "duracao": 2, "deadline_day": "Sexta", "deadline_hour": 17}]},
    {"nome": "Banco de Dados 1", "inicio": 8, "fim": 10, "dias": ["Sexta"],
     "atividades": [{"nome": "Prática SQL", "duracao": 2, "deadline_day": "Sexta", "deadline_hour": 20}]},
    {"nome": "Redes de Computadores", "inicio": 9, "fim": 11, "dias": ["Sexta"],
     "atividades": [{"nome": "Estudo teórico (Redes)", "duracao": 2, "deadline_day": "Sexta", "deadline_hour": 16}]},
    # Exemplos adicionais com par Segunda-Sexta
    {"nome": "Projeto de Algoritmos", "inicio": 13, "fim": 15, "dias": ["Segunda", "Sexta"],
     "atividades": [{"nome": "Implementação (Projeto)", "duracao": 4, "deadline_day": "Sexta", "deadline_hour": 23}]},
    {"nome": "Estruturas de Dados 2", "inicio": 15, "fim": 16, "dias": ["Segunda", "Sexta"],
     "atividades": [{"nome": "Trabalhos (ED2)", "duracao": 2, "deadline_day": "Sexta", "deadline_hour": 18}]},
]
